name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  NODE_VERSION: 12

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn lint:js

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn test

  ember-try:
    name: "Ember Try"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        try-scenario:
          [
            ember-lts-3.16,
            ember-lts-3.20,
            ember-beta,
            ember-canary,
            ember-default-with-jquery,
            embroider-safe,
            embroider-optimized,
          ]
    continue-on-error: ${{ matrix.try-scenario == 'ember-beta' || matrix.try-scenario == 'ember-canary' }}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn ember try:one ${{ matrix.try-scenario }}
        timeout-minutes: 10
